DROP DATABASE ironarena;

DROP USER 'ironarenauser'@'localhost';

flush privileges;

CREATE DATABASE ironarena;

USE ironarena;

CREATE TABLE players (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
firstname VARCHAR(20) NOT NULL,
lastname VARCHAR(20) NOT NULL,
location VARCHAR(20) NOT NULL,
forumname VARCHAR(20) NOT NULL,
email VARCHAR(30) NOT NULL,
code VARCHAR(8) NOT NULL,
creationdate TIMESTAMP(8) DEFAULT NOW(),
lastgamedate TIMESTAMP(8),
points INT(5) NOT NULL DEFAULT 0,
staff BOOLEAN NOT NULL DEFAULT FALSE,
played25 BOOLEAN NOT NULL DEFAULT FALSE,
played35 BOOLEAN NOT NULL DEFAULT FALSE,
played50 BOOLEAN NOT NULL DEFAULT FALSE,
played75 BOOLEAN NOT NULL DEFAULT FALSE,
played100 BOOLEAN NOT NULL DEFAULT FALSE,
playedall BOOLEAN NOT NULL DEFAULT FALSE,
numgames INT(5) NOT NULL DEFAULT 0,
numplayers INT(5) NOT NULL DEFAULT 0,
locationlist VARCHAR(255) NOT NULL DEFAULT "NONE",
factionlist VARCHAR(50) NOT NULL DEFAULT "NONE",
vsstaff BOOLEAN NOT NULL DEFAULT FALSE,
event1 BOOLEAN NOT NULL DEFAULT FALSE,
event2 BOOLEAN NOT NULL DEFAULT FALSE,
event3 BOOLEAN NOT NULL DEFAULT FALSE,
event4 BOOLEAN NOT NULL DEFAULT FALSE,
event5 BOOLEAN NOT NULL DEFAULT FALSE,
event6 BOOLEAN NOT NULL DEFAULT FALSE,
event7 BOOLEAN NOT NULL DEFAULT FALSE,
event8 BOOLEAN NOT NULL DEFAULT FALSE,
event9 BOOLEAN NOT NULL DEFAULT FALSE,
event10 BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE games (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
playerlist VARCHAR(255),
sizelist VARCHAR(255),
scenario BOOLEAN NOT NULL DEFAULT FALSE,
teamgame BOOLEAN NOT NULL DEFAULT FALSE,
newplayer BOOLEAN NOT NULL DEFAULT FALSE,
newlocation BOOLEAN NOT NULL DEFAULT FALSE,
fullypainted BOOLEAN NOT NULL DEFAULT FALSE,
gametime TIMESTAMP(8)
);

CREATE TABLE settings (
name VARCHAR(50) NOT NULL,
teamgame INT(5) NOT NULL DEFAULT 1,
newopponent INT(5) NOT NULL DEFAULT 1,
outofstate INT(5) NOT NULL DEFAULT 1,
fullypainted INT(5) NOT NULL DEFAULT 1,
scenariotable INT(5) NOT NULL DEFAULT 1,
played25 INT(5) NOT NULL DEFAULT 1,
played35 INT(5) NOT NULL DEFAULT 2,
played50 INT(5) NOT NULL DEFAULT 3,
played75 INT(5) NOT NULL DEFAULT 4,
played100 INT(5) NOT NULL DEFAULT 5,
playedall INT(5) NOT NULL DEFAULT 5,
numgames VARCHAR(255) NOT NULL,
numplayers VARCHAR(255) NOT NULL,
numlocations VARCHAR(255) NOT NULL,
numfactions VARCHAR(255) NOT NULL,
vsstaff INT(5) NOT NULL DEFAULT 2,
event1 INT(5) NOT NULL DEFAULT 15,
event2 INT(5) NOT NULL DEFAULT 0,
event3 INT(5) NOT NULL DEFAULT 0,
event4 INT(5) NOT NULL DEFAULT 0,
event5 INT(5) NOT NULL DEFAULT 0,
event6 INT(5) NOT NULL DEFAULT 0,
event7 INT(5) NOT NULL DEFAULT 0,
event8 INT(5) NOT NULL DEFAULT 0,
event9 INT(5) NOT NULL DEFAULT 0,
event10 INT(5) NOT NULL DEFAULT 0,
event1name VARCHAR(255),
event2name VARCHAR(255),
event3name VARCHAR(255),
event4name VARCHAR(255),
event5name VARCHAR(255),
event6name VARCHAR(255),
event7name VARCHAR(255),
event8name VARCHAR(255),
event9name VARCHAR(255),
event10name VARCHAR(255),
gametimelimit INT(20) NOT NULL DEFAULT 60
);

INSERT INTO settings (name, numgames, numplayers, numlocations, numfactions, event1name) 
		VALUES('Prototype', '5,1;10,2;15,3;20,4;25,5', '5,1;10,2;15,3;20,4;25,5', '5,1;10,2;15,3;20,4;25,5', '11,5', 'Hardcore Tournament');

CREATE TABLE payouts (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
playerid INT(5) NOT NULL,
points INT(5) NOT NULL,
notes VARCHAR(255),
time TIMESTAMP(8)
);
 
CREATE USER 'ironarenauser'@'localhost' IDENTIFIED BY 'iwantskullz';
GRANT INSERT, SELECT, UPDATE on players to 'ironarenauser'@'localhost';
GRANT INSERT, SELECT, UPDATE on games to 'ironarenauser'@'localhost';
GRANT INSERT, SELECT, UPDATE on payouts to 'ironarenauser'@'localhost';
GRANT INSERT, SELECT, UPDATE on settings to 'ironarenauser'@'localhost';

flush privileges;
